[nvchecker]
source = "github"
github = "milkv-duo/duo-buildroot-sdk-v2"
use_latest_release = true

[entities]
image-combo = [
    "buildroot-sdk-milkv-duo",
    "buildroot-sdk-milkv-duo256m",
    "buildroot-sdk-milkv-duos-sd",
    "buildroot-sdk-milkv-duo256m-python",
    "buildroot-sdk-milkv-duo-python",
]

[match]
buildroot-sdk-milkv-duo256m-python = ""
buildroot-sdk-milkv-duo-python = ""
