[nvchecker]
source = "regex"
url = "https://mirror.iscas.ac.cn/FreeBSD/releases/riscv/riscv64/ISO-IMAGES/"
regex = '<a href="([\d.]+)/" title="[\d.]+">[\d.]+/</a>'

[source]
regex_file_url = "{{nvchecker.url}}{{upstream_version}}/"
regex_file_regex = '<a href="([a-zA-Z0-9-.]+)" title="[a-zA-Z0-9-.]+">[a-zA-Z0-9-.]+</a>'

[entities]
image-combo = [
    "freebsd-riscv64-mini-live",
]
