[nvchecker]
source = "regex"
url = "https://mirror.iscas.ac.cn/revyos/extra/images/lcon4a/"
regex = '<a href="([\d.]+)/">[\d.]+/</a>'

[entities]
image-combo = [
    "revyos-sipeed-lcon4a",
    "uboot-revyos-sipeed-lcon4a-8g",
    "uboot-revyos-sipeed-lcon4a-16g"
]
