[nvchecker]
source = "regex"
url = "https://archive.spacemit.com/image/k1/version/bianbu/"
regex = '<a href="(v[\d.]+)/">[v\d.]+/</a>'

[source]
regex_file_url = "{{nvchecker.url}}{{upstream_version}}/"
# skip alpha, beta, rc versions
regex_file_regex = '<a href="(bianbu.+)">bianbu.+</a>'

[entities]
image-combo = [
    "bianbu-minimal-spacemit-k1",
    "bianbu-minimal-spacemit-k1-sd",
    "bianbu-desktop-spacemit-k1",
    "bianbu-desktop-spacemit-k1-sd",
    "bianbu-desktop-lite-spacemit-k1",
    "bianbu-desktop-lite-spacemit-k1-sd",
]
