[nvchecker]
source = "regex"
url = "https://mirror.iscas.ac.cn/revyos/extra/images/lpi4a/"
regex = '<a href="([\d.]+)/">[\d.]+/</a>'

[entities]
image-combo = [
    "revyos-sipeed-lpi4a",
    "uboot-revyos-sipeed-lpi4a-8g",
    "uboot-revyos-sipeed-lpi4a-16g"
]

[policies]
# uboot not upgrade in each release
# sometimes their hashes are the same with old version
# see: https://github.com/ruyisdk/packages-index/pull/76
# so use `keep_back` policy here
uboot-revyos-sipeed-lpi4a-8g = ["keep_back"]
uboot-revyos-sipeed-lpi4a-16g = ["keep_back"]
